EQ(
    COUNT(
        LT(
            CLOSE,EMA(CLOSE,60)
        ),
        BARSLAST(
            AND(
                GT(
                    EMA(CLOSE,40),
                    EMA(CLOSE,60)
                ),
                OR(
                    EQ(
                        EMA(CLOSE,20),
                        EMA(CLOSE,40)
                    ),
                    GT(
                        EMA(CLOSE,20),
                        EMA(CLOSE,40)
                    )
                )
            )
        )
    ),
    BARSLAST(
        AND(
            GT(
                EMA(CLOSE,40),
                EMA(CLOSE,60)
            ),
            OR(
                EQ(
                    EMA(CLOSE,20),
                    EMA(CLOSE,40)
                ),
                GT(
                    EMA(CLOSE,20),
                    EMA(CLOSE,40)
                )
            )
        )
    )
)